In [24]:
# 페키지 불러오기
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
plt.style.use('fivethirtyeight')
from scipy.stats import norm
from sklearn.preprocessing import StandardScaler
from scipy import stats
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBRegressor
import xgboost
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
plt.rcParams['font.size'] = 15
import warnings 
warnings.filterwarnings(action='ignore')

In [43]:
EDA = pd.read_csv('EDA.csv',encoding='cp949')

In [44]:
EDA.head()

,gid,geometry,four,six,seven,2018,2019,2020,2021,seventeen,eighteen,nineteen,twenty,twentyone,two,cctv
0,마라231909,MULTIPOLYGON (((128.8523707124823 35.205903552...,10,2,0,0,0,0,0,0,0,0,0,0,0,0
1,마라154986,MULTIPOLYGON (((128.7688788763629 35.276233217...,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,마라213944,MULTIPOLYGON (((128.833116749215 35.2376741072...,9,0,0,0,0,0,0,0,0,0,0,0,0,0
3,마마105025,MULTIPOLYGON (((128.7155376522062 35.311944657...,0,0,1,0,0,0,0,0,0,0,0,0,0,3
4,마라202940,MULTIPOLYGON (((128.8209718821295 35.234200772...,48,2,0,0,0,0,0,0,0,0,1,0,0,0

In [56]:
EDA1 = EDA[EDA['cctv'] >= 1]

In [57]:
EDA1.head()

,gid,geometry,four,six,seven,2018,2019,2020,2021,seventeen,eighteen,nineteen,twenty,twentyone,two,cctv,pred
3,마마105025,MULTIPOLYGON (((128.7155376522062 35.311944657...,0,0,1,0,0,0,0,0,0,0,0,0,0,3,39.230633
6,마라142954,MULTIPOLYGON (((128.7552421328997 35.247523262...,21,4,0,0,0,0,0,0,0,0,0,0,0,1,11.386763
20,마라281955,MULTIPOLYGON (((128.9080022709618 35.246743775...,397,6,1,176,156,122,125,1,0,0,0,0,0,5,363.068878
22,마라273935,MULTIPOLYGON (((128.8989018157547 35.228816966...,234,0,1,306,312,247,213,0,0,0,0,0,0,4,221.161041
26,마라186890,MULTIPOLYGON (((128.8026719911344 35.189317442...,15,5,1,0,0,0,0,0,0,0,0,0,0,3,30.074039

In [47]:
x_train = EDA1[['six', 'seven', '2018', '2019', '2020', '2021','seventeen','eighteen','nineteen','twenty','twentyone','two','cctv']]
y_train = EDA1['four']

In [48]:
x_test = EDA[['six', 'seven', '2018', '2019', '2020', '2021','seventeen','eighteen','nineteen','twenty','twentyone','two','cctv']]

In [49]:
import numpy as np
from sklearn.model_selection import KFold
import warnings
warnings.filterwarnings('ignore')

import xgboost as xgb

xgb_clf = xgb.XGBClassifier()

In [50]:
from sklearn.model_selection import GridSearchCV
import xgboost as xgb
from xgboost import XGBRegressor

param = {
    'max_depth':[2,3,4],
    'n_estimators':range(300,600,100), #  'n_estimators':range(600,700,50) 여기에 cv 10 (이거와 별반차이가 없다.)
    'colsample_bytree':[0.5,0.7,1],
    'colsample_bylevel':[0.5,0.7,1],
}
model = xgb.XGBRegressor()
grid_search = GridSearchCV(estimator=model, param_grid=param, cv=10, 
                           scoring='neg_mean_squared_error',
                           n_jobs=-1)

grid_search.fit(x_train, y_train)
print(grid_search.best_params_)
{'colsample_bylevel': 0.5, 'colsample_bytree': 0.5, 'max_depth': 3, 'n_estimators': 600}
XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.5,
             colsample_bytree=0.7, gamma=0, learning_rate=0.1, max_delta_step=0,
             max_depth=3, min_child_weight=1, missing=None, n_estimators=600,
             n_jobs=1, nthread=None, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=True, subsample=1)

{'colsample_bylevel': 0.7, 'colsample_bytree': 0.5, 'max_depth': 3, 'n_estimators': 300}

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.5,
             colsample_bynode=None, colsample_bytree=0.7,
             enable_categorical=False, gamma=0, gpu_id=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=None, monotone_constraints=None,
             n_estimators=600, n_jobs=1, nthread=None, num_parallel_tree=None,
             objective='reg:linear', predictor=None, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
             silent=True, subsample=1, tree_method=None, ...)

In [51]:
y_pred = grid_search.predict(x_test)

In [52]:
y_pred

array([12.000923, 17.841326, 17.841326, ..., 17.841326, 17.841326,
       17.841326], dtype=float32)

In [53]:
EDA['pred']=y_pred

In [54]:
EDA.head()

,gid,geometry,four,six,seven,2018,2019,2020,2021,seventeen,eighteen,nineteen,twenty,twentyone,two,cctv,pred
0,마라231909,MULTIPOLYGON (((128.8523707124823 35.205903552...,10,2,0,0,0,0,0,0,0,0,0,0,0,0,12.000923
1,마라154986,MULTIPOLYGON (((128.7688788763629 35.276233217...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,17.841326
2,마라213944,MULTIPOLYGON (((128.833116749215 35.2376741072...,9,0,0,0,0,0,0,0,0,0,0,0,0,0,17.841326
3,마마105025,MULTIPOLYGON (((128.7155376522062 35.311944657...,0,0,1,0,0,0,0,0,0,0,0,0,0,3,39.230633
4,마라202940,MULTIPOLYGON (((128.8209718821295 35.234200772...,48,2,0,0,0,0,0,0,0,0,1,0,0,0,63.766861

In [55]:
EDA.sort_values(by=['pred'],ascending=False)

,gid,geometry,four,six,seven,2018,2019,2020,2021,seventeen,eighteen,nineteen,twenty,twentyone,two,cctv,pred
488,마라258935,MULTIPOLYGON (((128.882422588875 35.2290063205...,4998,2,0,93,88,98,104,0,0,0,16,0,0,2,5000.015137
5695,마라247971,MULTIPOLYGON (((128.8708839231963 35.261595912...,549,0,0,72,64,51,51,0,0,0,18,0,0,0,2005.272339
6846,마라278952,MULTIPOLYGON (((128.9046590776117 35.244077783...,1008,6,0,123,119,139,147,0,0,0,10,0,0,0,1910.320923
2172,마라243939,MULTIPOLYGON (((128.8660036604245 35.232799242...,1880,10,1,82,78,86,86,0,0,0,21,0,0,5,1882.857178
2722,마라279952,MULTIPOLYGON (((128.9057578903404 35.244065022...,502,42,0,123,119,121,128,0,0,0,10,0,0,0,1851.339111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4732,마라238933,MULTIPOLYGON (((128.8604199488788 35.227452393...,7,0,0,21,24,253,269,0,0,0,0,0,0,0,-135.727036
3051,마라200879,MULTIPOLYGON (((128.81788551003 35.17923482644...,17,0,0,0,0,244,245,0,0,0,0,0,0,0,-143.078278
1511,마라223943,MULTIPOLYGON (((128.8440894380464 35.236651109...,6,0,0,0,0,147,148,0,0,0,0,0,0,0,-146.278244
7884,마라210860,MULTIPOLYGON (((128.8285865804827 35.161986808...,9,0,0,0,0,177,193,0,0,0,0,0,0,0,-153.925568
3540,마라243971,MULTIPOLYGON (((128.8664876568521 35.261645648...,38,0,0,0,0,172,137,0,0,0,0,0,0,0,-186.990463